name: Build App & Deploy Internal

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/common-build-workflow.yml
    secrets: inherit
    with:
      upload-artifact: true


  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download aab
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
      - name: Decode Base64 Keystore
        
        env:
          JSON_KEY_BASE64: ${{ secrets.ANDROID_API_JSON_KEY }}
        run: echo $JSON_KEY_BASE64 | base64 --decode > publish.json

      - name: Deploy on Google Play Internal Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./publish.json
          packageName: com.lolo.io.onelist
          releaseFiles: app-release.aab
          whatsNewDirectory: whatsnew
          track: internal
  